use meta_signal_criome::{
    META_CRIOME_INTERFACE_RUST, META_CRIOME_INTERFACE_SOURCE, bootstrap_manifest,
};

#[test]
fn owner_source_imports_the_exact_producer_and_keeps_roles_empty() {
    assert!(META_CRIOME_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[signal_criome:lib.["));
    assert!(META_CRIOME_INTERFACE_SOURCE.contains("OwnerRequest.["));
    assert!(META_CRIOME_INTERFACE_SOURCE.contains("OwnerReply.["));
    assert!(META_CRIOME_INTERFACE_SOURCE.contains("\n  []\n  []\n  []\n  ["));
    assert!(!META_CRIOME_INTERFACE_SOURCE.contains("Optional."));
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    assert!(META_CRIOME_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["OwnerRequest", "OwnerReply", "AuthorizationApproval"] {
        assert!(!META_CRIOME_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
        assert!(!META_CRIOME_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
    }
    assert!(META_CRIOME_INTERFACE_RUST.contains("signal_criome::schema::lib::z"));
    assert!(bootstrap_manifest::DECLARATION_SEATS.len() > 60);
}

#[test]
fn retired_schema_source_is_absent() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    assert!(!root.join("schema/lib.schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
}
