// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VQPE(u64);
impl z2VQPE {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2Vdzj {z2VM7Y , z2VMy3 , z2VTT2 ,} 
pub struct z2VYg3 {}
pub struct z2VYYB {
    pub field_0: z2Vdzj,
    pub field_1: Vec<z2VP73>,
}
pub enum z2VSN6 {z2Vdyw , z2VWqd , z2VZDb , z2VNcf ,} 
pub enum z2VKtS {
    z2VR4u(z2VWz5),
    z2VcU1(signal_criome::schema::lib::z2VSGX),
    z2VXTq(z2VYg3),
    z2VZJf(z2VWbk),
    z2VNKR(signal_criome::schema::lib::z2VXWs),
    z2VYmK(signal_criome::schema::lib::z2VS9T),
    z2VYir(signal_criome::schema::lib::z2VdtA),
    z2VU18(signal_criome::schema::lib::z2VUjo),
    z2VbVk(z2VMDj),
    z2VYdA(signal_criome::schema::lib::z2VUjo),
    z2VVMU(z2VYDr),
    z2Var1(z2VSjN),
    z2VMWd(signal_criome::schema::lib::z2VNo7),
    z2VX8U(z2VYg3),
}
pub struct z2VR26 {
    pub field_0: z2VVVL,
    pub field_1: z2VVm5,
}
pub struct z2VMDj {
    pub field_0: signal_criome::schema::lib::z2VSrE,
}
pub struct z2VSjN {
    pub field_0: signal_criome::schema::lib::z2VWaA,
    pub field_1: signal_criome::schema::lib::z2VSrE,
}
pub struct z2VYDr(std::string::String);
impl z2VYDr {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VYmf {
    pub field_0: z2VQPE,
}
pub enum z2VNfL {z2VcPz , z2VevL , z2VYjP ,} 
pub struct z2VWbk {
    pub field_0: signal_criome::schema::lib::z2VUph,
    pub field_1: z2VNfL,
}
pub enum z2VVm5 {z2VYmh , z2VYBX ,} 
pub struct z2VXr4 {
    pub field_0: z2VZJN,
}
pub struct z2VP73 {
    pub field_0: signal_criome::schema::lib::z2VWaA,
    pub field_1: signal_criome::schema::lib::z2VSrE,
    pub field_2: signal_criome::schema::lib::z2VL5X,
}
pub struct z2VXNG {
    pub field_0: signal_criome::schema::lib::z2VWaA,
    pub field_1: signal_criome::schema::lib::z2VPfK,
}
pub struct z2VUHx {
    pub field_0: signal_criome::schema::lib::z2VUph,
    pub field_1: z2VNfL,
}
pub struct z2VWz5 {}
pub enum z2VZJN {z2VdFh , z2VMLC , z2VT22 ,} 
pub enum z2VUG9 {
    z2VbK6(z2VTPp),
    z2VMVt(z2VYmf),
    z2VS5r(z2VUHx),
    z2VWCn(z2VR26),
    z2VPTr(signal_criome::schema::lib::z2VShF),
    z2VdGy(z2VYDr),
    z2VS59(signal_criome::schema::lib::z2Vb3U),
    z2VXBy(signal_criome::schema::lib::z2VfB8),
    z2VTAm(signal_criome::schema::lib::z2Vb3U),
    z2Veff(signal_criome::schema::lib::z2VRAT),
    z2VQJa(signal_criome::schema::lib::z2VW3f),
    z2VYP9(signal_criome::schema::lib::z2VfB8),
    z2VP45(signal_criome::schema::lib::z2VUEA),
    z2VKp1(z2VXr4),
    z2VYiQ(z2VXNG),
    z2VMm2(z2VYYB),
}
pub enum z2VRAr {
    z2VR4c(signal_criome::schema::lib::z2VfB8),
    z2Va6Z(signal_criome::schema::lib::z2VfB8),
    z2VLtX(signal_criome::schema::lib::z2VShF),
}
pub enum z2VVVL {z2VMy4 , z2VSiM , z2VeK1 , z2VM1b , z2VR3N , z2Vbaa , z2VLYL , z2VMHx , z2VerJ , z2VLVL , z2VcS1 , z2Vb59 , z2VLLW , z2VTPW ,} 
pub struct z2VTPp {
    pub field_0: z2VSN6,
}
