// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_criome::schema::lib::CriomeDaemonConfiguration as CriomeDaemonConfiguration;
#[rustfmt::skip]
pub use signal_criome::schema::lib::AuthorizationRequestSlot as AuthorizationRequestSlot;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedAuthorizationObservation as ParkedAuthorizationObservation;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedAuthorizationSnapshot as ParkedAuthorizationSnapshot;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyIdentifier as InterceptPolicyIdentifier;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyProposal as InterceptPolicyProposal;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicy as InterceptPolicy;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ActiveInterceptPolicies as ActiveInterceptPolicies;
#[rustfmt::skip]
pub use signal_criome::schema::lib::InterceptPolicyCancellation as InterceptPolicyCancellation;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestQuery as ParkedRequestQuery;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestSnapshot as ParkedRequestSnapshot;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestAnswer as ParkedRequestAnswer;
#[rustfmt::skip]
pub use signal_criome::schema::lib::ParkedRequestResolution as ParkedRequestResolution;
#[rustfmt::skip]
pub use signal_criome::schema::lib::RootAnchorDigest as RootAnchorDigest;
#[rustfmt::skip]
pub use signal_criome::schema::lib::RootGenesis as RootGenesis;
#[rustfmt::skip]
pub use signal_criome::schema::lib::FoundingSignature as FoundingSignature;
#[rustfmt::skip]
pub use signal_criome::schema::lib::Identity as Identity;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigurationGeneration(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Configured(ConfigurationGeneration);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ConfigurationRejectionReason {
    ManagerAuthorityRequired,
    MalformedConfiguration,
    StoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ConfigurationRejected(ConfigurationRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AuthorizationApprovalDecision {
    Approve,
    Reject,
    Defer,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationApproval {
    pub authorization_request_slot: AuthorizationRequestSlot,
    pub authorization_approval_decision: AuthorizationApprovalDecision,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AuthorizationApprovalRecorded {
    pub authorization_request_slot: AuthorizationRequestSlot,
    pub authorization_approval_decision: AuthorizationApprovalDecision,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingAcceptance {
    pub root_anchor_digest: RootAnchorDigest,
    pub root_genesis: RootGenesis,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RootFoundingRejectionReason {
    CohortMismatch,
    AlreadyFounded,
    ManagerAuthorityRequired,
    MalformedGenesis,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingAccepted {
    pub root_anchor_digest: RootAnchorDigest,
    pub founding_signature: FoundingSignature,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingRejected(RootFoundingRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingInitiation(RootGenesis);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingObservation {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RootFoundingState {
    Unfounded,
    Gathering,
    Founded,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PendingFounding {
    pub root_anchor_digest: RootAnchorDigest,
    pub root_genesis: RootGenesis,
    pub identity: Identity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RootFoundingStatus {
    pub root_founding_state: RootFoundingState,
    pub pending_founding_vector: Vec<PendingFounding>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterceptPolicyObservation {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum InterceptPolicyChange {
    Created(InterceptPolicy),
    Replaced(InterceptPolicy),
    Cancelled(InterceptPolicyIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InterceptPolicyStreamToken(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Configure,
    CreateInterceptPolicy,
    ReplaceInterceptPolicy,
    CancelInterceptPolicy,
    ListInterceptPolicies,
    ObserveInterceptPolicies,
    RetractInterceptPolicyObservation,
    FetchParkedRequests,
    AnswerParkedRequest,
    ObserveParkedAuthorizations,
    SubmitAuthorizationApproval,
    AcceptRootFounding,
    InitiateRootFounding,
    ObserveRootFounding,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotBuiltYet,
    DependencyNotReady,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented {
    pub operation_kind: OperationKind,
    pub unimplemented_reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Configure(CriomeDaemonConfiguration),
    CreateInterceptPolicy(InterceptPolicyProposal),
    ReplaceInterceptPolicy(InterceptPolicyProposal),
    CancelInterceptPolicy(InterceptPolicyCancellation),
    ListInterceptPolicies(InterceptPolicyObservation),
    ObserveInterceptPolicies(InterceptPolicyObservation),
    RetractInterceptPolicyObservation(InterceptPolicyStreamToken),
    FetchParkedRequests(ParkedRequestQuery),
    AnswerParkedRequest(ParkedRequestAnswer),
    ObserveParkedAuthorizations(ParkedAuthorizationObservation),
    SubmitAuthorizationApproval(AuthorizationApproval),
    AcceptRootFounding(RootFoundingAcceptance),
    InitiateRootFounding(RootFoundingInitiation),
    ObserveRootFounding(RootFoundingObservation),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ConfigurationApplied(Configured),
    InterceptPolicyCreated(InterceptPolicy),
    InterceptPolicyReplaced(InterceptPolicy),
    InterceptPolicyCancelled(InterceptPolicyIdentifier),
    InterceptPoliciesListed(ActiveInterceptPolicies),
    InterceptPolicyObservationOpened(ActiveInterceptPolicies),
    InterceptPolicyObservationRetracted(InterceptPolicyStreamToken),
    ParkedRequestsFetched(ParkedRequestSnapshot),
    ParkedRequestAnswered(ParkedRequestResolution),
    ParkedAuthorizations(ParkedAuthorizationSnapshot),
    AuthorizationApprovalStored(AuthorizationApprovalRecorded),
    ConfigurationRefused(ConfigurationRejected),
    OperationUnimplemented(RequestUnimplemented),
    RootFoundingConfirmed(RootFoundingAccepted),
    RootFoundingRefused(RootFoundingRejected),
    RootFoundingObserved(RootFoundingStatus),
}

#[rustfmt::skip]
impl ConfigurationGeneration {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for ConfigurationGeneration {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Configured {
    pub fn new(payload: ConfigurationGeneration) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ConfigurationGeneration {
        &self.0
    }
    pub fn into_payload(self) -> ConfigurationGeneration {
        self.0
    }
}
#[rustfmt::skip]
impl From<ConfigurationGeneration> for Configured {
    fn from(payload: ConfigurationGeneration) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConfigurationRejected {
    pub fn new(payload: ConfigurationRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ConfigurationRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> ConfigurationRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<ConfigurationRejectionReason> for ConfigurationRejected {
    fn from(payload: ConfigurationRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RootFoundingRejected {
    pub fn new(payload: RootFoundingRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RootFoundingRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> RootFoundingRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<RootFoundingRejectionReason> for RootFoundingRejected {
    fn from(payload: RootFoundingRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RootFoundingInitiation {
    pub fn new(payload: RootGenesis) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RootGenesis {
        &self.0
    }
    pub fn into_payload(self) -> RootGenesis {
        self.0
    }
}
#[rustfmt::skip]
impl From<RootGenesis> for RootFoundingInitiation {
    fn from(payload: RootGenesis) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InterceptPolicyStreamToken {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for InterceptPolicyStreamToken {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InterceptPolicyChange {
    pub fn created(payload: InterceptPolicy) -> Self {
        Self::Created(payload)
    }
    pub fn replaced(payload: InterceptPolicy) -> Self {
        Self::Replaced(payload)
    }
    pub fn cancelled(payload: InterceptPolicyIdentifier) -> Self {
        Self::Cancelled(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn configure(payload: CriomeDaemonConfiguration) -> Self {
        Self::Configure(payload)
    }
    pub fn create_intercept_policy(payload: InterceptPolicyProposal) -> Self {
        Self::CreateInterceptPolicy(payload)
    }
    pub fn replace_intercept_policy(payload: InterceptPolicyProposal) -> Self {
        Self::ReplaceInterceptPolicy(payload)
    }
    pub fn cancel_intercept_policy(payload: InterceptPolicyCancellation) -> Self {
        Self::CancelInterceptPolicy(payload)
    }
    pub fn list_intercept_policies(payload: InterceptPolicyObservation) -> Self {
        Self::ListInterceptPolicies(payload)
    }
    pub fn observe_intercept_policies(payload: InterceptPolicyObservation) -> Self {
        Self::ObserveInterceptPolicies(payload)
    }
    pub fn retract_intercept_policy_observation(payload: String) -> Self {
        Self::RetractInterceptPolicyObservation(InterceptPolicyStreamToken::new(payload))
    }
    pub fn fetch_parked_requests(payload: ParkedRequestQuery) -> Self {
        Self::FetchParkedRequests(payload)
    }
    pub fn answer_parked_request(payload: ParkedRequestAnswer) -> Self {
        Self::AnswerParkedRequest(payload)
    }
    pub fn observe_parked_authorizations(
        payload: ParkedAuthorizationObservation,
    ) -> Self {
        Self::ObserveParkedAuthorizations(payload)
    }
    pub fn submit_authorization_approval(payload: AuthorizationApproval) -> Self {
        Self::SubmitAuthorizationApproval(payload)
    }
    pub fn accept_root_founding(payload: RootFoundingAcceptance) -> Self {
        Self::AcceptRootFounding(payload)
    }
    pub fn initiate_root_founding(payload: RootGenesis) -> Self {
        Self::InitiateRootFounding(RootFoundingInitiation::new(payload))
    }
    pub fn observe_root_founding(payload: RootFoundingObservation) -> Self {
        Self::ObserveRootFounding(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn configuration_applied(payload: ConfigurationGeneration) -> Self {
        Self::ConfigurationApplied(Configured::new(payload))
    }
    pub fn intercept_policy_created(payload: InterceptPolicy) -> Self {
        Self::InterceptPolicyCreated(payload)
    }
    pub fn intercept_policy_replaced(payload: InterceptPolicy) -> Self {
        Self::InterceptPolicyReplaced(payload)
    }
    pub fn intercept_policy_cancelled(payload: InterceptPolicyIdentifier) -> Self {
        Self::InterceptPolicyCancelled(payload)
    }
    pub fn intercept_policies_listed(payload: ActiveInterceptPolicies) -> Self {
        Self::InterceptPoliciesListed(payload)
    }
    pub fn intercept_policy_observation_opened(
        payload: ActiveInterceptPolicies,
    ) -> Self {
        Self::InterceptPolicyObservationOpened(payload)
    }
    pub fn intercept_policy_observation_retracted(payload: String) -> Self {
        Self::InterceptPolicyObservationRetracted(
            InterceptPolicyStreamToken::new(payload),
        )
    }
    pub fn parked_requests_fetched(payload: ParkedRequestSnapshot) -> Self {
        Self::ParkedRequestsFetched(payload)
    }
    pub fn parked_request_answered(payload: ParkedRequestResolution) -> Self {
        Self::ParkedRequestAnswered(payload)
    }
    pub fn parked_authorizations(payload: ParkedAuthorizationSnapshot) -> Self {
        Self::ParkedAuthorizations(payload)
    }
    pub fn authorization_approval_stored(
        payload: AuthorizationApprovalRecorded,
    ) -> Self {
        Self::AuthorizationApprovalStored(payload)
    }
    pub fn configuration_refused(payload: ConfigurationRejectionReason) -> Self {
        Self::ConfigurationRefused(ConfigurationRejected::new(payload))
    }
    pub fn operation_unimplemented(payload: RequestUnimplemented) -> Self {
        Self::OperationUnimplemented(payload)
    }
    pub fn root_founding_confirmed(payload: RootFoundingAccepted) -> Self {
        Self::RootFoundingConfirmed(payload)
    }
    pub fn root_founding_refused(payload: RootFoundingRejectionReason) -> Self {
        Self::RootFoundingRefused(RootFoundingRejected::new(payload))
    }
    pub fn root_founding_observed(payload: RootFoundingStatus) -> Self {
        Self::RootFoundingObserved(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyIdentifier> for InterceptPolicyChange {
    fn from(payload: InterceptPolicyIdentifier) -> Self {
        Self::Cancelled(payload)
    }
}

#[rustfmt::skip]
impl From<CriomeDaemonConfiguration> for Input {
    fn from(payload: CriomeDaemonConfiguration) -> Self {
        Self::Configure(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyCancellation> for Input {
    fn from(payload: InterceptPolicyCancellation) -> Self {
        Self::CancelInterceptPolicy(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyStreamToken> for Input {
    fn from(payload: InterceptPolicyStreamToken) -> Self {
        Self::RetractInterceptPolicyObservation(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestQuery> for Input {
    fn from(payload: ParkedRequestQuery) -> Self {
        Self::FetchParkedRequests(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestAnswer> for Input {
    fn from(payload: ParkedRequestAnswer) -> Self {
        Self::AnswerParkedRequest(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedAuthorizationObservation> for Input {
    fn from(payload: ParkedAuthorizationObservation) -> Self {
        Self::ObserveParkedAuthorizations(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationApproval> for Input {
    fn from(payload: AuthorizationApproval) -> Self {
        Self::SubmitAuthorizationApproval(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingAcceptance> for Input {
    fn from(payload: RootFoundingAcceptance) -> Self {
        Self::AcceptRootFounding(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingInitiation> for Input {
    fn from(payload: RootFoundingInitiation) -> Self {
        Self::InitiateRootFounding(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingObservation> for Input {
    fn from(payload: RootFoundingObservation) -> Self {
        Self::ObserveRootFounding(payload)
    }
}

#[rustfmt::skip]
impl From<Configured> for Output {
    fn from(payload: Configured) -> Self {
        Self::ConfigurationApplied(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyIdentifier> for Output {
    fn from(payload: InterceptPolicyIdentifier) -> Self {
        Self::InterceptPolicyCancelled(payload)
    }
}

#[rustfmt::skip]
impl From<InterceptPolicyStreamToken> for Output {
    fn from(payload: InterceptPolicyStreamToken) -> Self {
        Self::InterceptPolicyObservationRetracted(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestSnapshot> for Output {
    fn from(payload: ParkedRequestSnapshot) -> Self {
        Self::ParkedRequestsFetched(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedRequestResolution> for Output {
    fn from(payload: ParkedRequestResolution) -> Self {
        Self::ParkedRequestAnswered(payload)
    }
}

#[rustfmt::skip]
impl From<ParkedAuthorizationSnapshot> for Output {
    fn from(payload: ParkedAuthorizationSnapshot) -> Self {
        Self::ParkedAuthorizations(payload)
    }
}

#[rustfmt::skip]
impl From<AuthorizationApprovalRecorded> for Output {
    fn from(payload: AuthorizationApprovalRecorded) -> Self {
        Self::AuthorizationApprovalStored(payload)
    }
}

#[rustfmt::skip]
impl From<ConfigurationRejected> for Output {
    fn from(payload: ConfigurationRejected) -> Self {
        Self::ConfigurationRefused(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::OperationUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingAccepted> for Output {
    fn from(payload: RootFoundingAccepted) -> Self {
        Self::RootFoundingConfirmed(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingRejected> for Output {
    fn from(payload: RootFoundingRejected) -> Self {
        Self::RootFoundingRefused(payload)
    }
}

#[rustfmt::skip]
impl From<RootFoundingStatus> for Output {
    fn from(payload: RootFoundingStatus) -> Self {
        Self::RootFoundingObserved(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_CONFIGURE: u64 = 0x0000000000000000;
    pub const INPUT_CREATE_INTERCEPT_POLICY: u64 = 0x0001000000000000;
    pub const INPUT_REPLACE_INTERCEPT_POLICY: u64 = 0x0002000000000000;
    pub const INPUT_CANCEL_INTERCEPT_POLICY: u64 = 0x0003000000000000;
    pub const INPUT_LIST_INTERCEPT_POLICIES: u64 = 0x0004000000000000;
    pub const INPUT_OBSERVE_INTERCEPT_POLICIES: u64 = 0x0005000000000000;
    pub const INPUT_RETRACT_INTERCEPT_POLICY_OBSERVATION: u64 = 0x0006000000000000;
    pub const INPUT_FETCH_PARKED_REQUESTS: u64 = 0x0007000000000000;
    pub const INPUT_ANSWER_PARKED_REQUEST: u64 = 0x0008000000000000;
    pub const INPUT_OBSERVE_PARKED_AUTHORIZATIONS: u64 = 0x0009000000000000;
    pub const INPUT_SUBMIT_AUTHORIZATION_APPROVAL: u64 = 0x000A000000000000;
    pub const INPUT_ACCEPT_ROOT_FOUNDING: u64 = 0x000B000000000000;
    pub const INPUT_INITIATE_ROOT_FOUNDING: u64 = 0x000C000000000000;
    pub const INPUT_OBSERVE_ROOT_FOUNDING: u64 = 0x000D000000000000;
    pub const OUTPUT_CONFIGURATION_APPLIED: u64 = 0x0100000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_CREATED: u64 = 0x0101000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_REPLACED: u64 = 0x0102000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_CANCELLED: u64 = 0x0103000000000000;
    pub const OUTPUT_INTERCEPT_POLICIES_LISTED: u64 = 0x0104000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_OBSERVATION_OPENED: u64 = 0x0105000000000000;
    pub const OUTPUT_INTERCEPT_POLICY_OBSERVATION_RETRACTED: u64 = 0x0106000000000000;
    pub const OUTPUT_PARKED_REQUESTS_FETCHED: u64 = 0x0107000000000000;
    pub const OUTPUT_PARKED_REQUEST_ANSWERED: u64 = 0x0108000000000000;
    pub const OUTPUT_PARKED_AUTHORIZATIONS: u64 = 0x0109000000000000;
    pub const OUTPUT_AUTHORIZATION_APPROVAL_STORED: u64 = 0x010A000000000000;
    pub const OUTPUT_CONFIGURATION_REFUSED: u64 = 0x010B000000000000;
    pub const OUTPUT_OPERATION_UNIMPLEMENTED: u64 = 0x010C000000000000;
    pub const OUTPUT_ROOT_FOUNDING_CONFIRMED: u64 = 0x010D000000000000;
    pub const OUTPUT_ROOT_FOUNDING_REFUSED: u64 = 0x010E000000000000;
    pub const OUTPUT_ROOT_FOUNDING_OBSERVED: u64 = 0x010F000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Configure,
    CreateInterceptPolicy,
    ReplaceInterceptPolicy,
    CancelInterceptPolicy,
    ListInterceptPolicies,
    ObserveInterceptPolicies,
    RetractInterceptPolicyObservation,
    FetchParkedRequests,
    AnswerParkedRequest,
    ObserveParkedAuthorizations,
    SubmitAuthorizationApproval,
    AcceptRootFounding,
    InitiateRootFounding,
    ObserveRootFounding,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ConfigurationApplied,
    InterceptPolicyCreated,
    InterceptPolicyReplaced,
    InterceptPolicyCancelled,
    InterceptPoliciesListed,
    InterceptPolicyObservationOpened,
    InterceptPolicyObservationRetracted,
    ParkedRequestsFetched,
    ParkedRequestAnswered,
    ParkedAuthorizations,
    AuthorizationApprovalStored,
    ConfigurationRefused,
    OperationUnimplemented,
    RootFoundingConfirmed,
    RootFoundingRefused,
    RootFoundingObserved,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Configure(_) => InputRoute::Configure,
            Self::CreateInterceptPolicy(_) => InputRoute::CreateInterceptPolicy,
            Self::ReplaceInterceptPolicy(_) => InputRoute::ReplaceInterceptPolicy,
            Self::CancelInterceptPolicy(_) => InputRoute::CancelInterceptPolicy,
            Self::ListInterceptPolicies(_) => InputRoute::ListInterceptPolicies,
            Self::ObserveInterceptPolicies(_) => InputRoute::ObserveInterceptPolicies,
            Self::RetractInterceptPolicyObservation(_) => {
                InputRoute::RetractInterceptPolicyObservation
            }
            Self::FetchParkedRequests(_) => InputRoute::FetchParkedRequests,
            Self::AnswerParkedRequest(_) => InputRoute::AnswerParkedRequest,
            Self::ObserveParkedAuthorizations(_) => {
                InputRoute::ObserveParkedAuthorizations
            }
            Self::SubmitAuthorizationApproval(_) => {
                InputRoute::SubmitAuthorizationApproval
            }
            Self::AcceptRootFounding(_) => InputRoute::AcceptRootFounding,
            Self::InitiateRootFounding(_) => InputRoute::InitiateRootFounding,
            Self::ObserveRootFounding(_) => InputRoute::ObserveRootFounding,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Configure(_) => short_header::INPUT_CONFIGURE,
            Self::CreateInterceptPolicy(_) => short_header::INPUT_CREATE_INTERCEPT_POLICY,
            Self::ReplaceInterceptPolicy(_) => {
                short_header::INPUT_REPLACE_INTERCEPT_POLICY
            }
            Self::CancelInterceptPolicy(_) => short_header::INPUT_CANCEL_INTERCEPT_POLICY,
            Self::ListInterceptPolicies(_) => short_header::INPUT_LIST_INTERCEPT_POLICIES,
            Self::ObserveInterceptPolicies(_) => {
                short_header::INPUT_OBSERVE_INTERCEPT_POLICIES
            }
            Self::RetractInterceptPolicyObservation(_) => {
                short_header::INPUT_RETRACT_INTERCEPT_POLICY_OBSERVATION
            }
            Self::FetchParkedRequests(_) => short_header::INPUT_FETCH_PARKED_REQUESTS,
            Self::AnswerParkedRequest(_) => short_header::INPUT_ANSWER_PARKED_REQUEST,
            Self::ObserveParkedAuthorizations(_) => {
                short_header::INPUT_OBSERVE_PARKED_AUTHORIZATIONS
            }
            Self::SubmitAuthorizationApproval(_) => {
                short_header::INPUT_SUBMIT_AUTHORIZATION_APPROVAL
            }
            Self::AcceptRootFounding(_) => short_header::INPUT_ACCEPT_ROOT_FOUNDING,
            Self::InitiateRootFounding(_) => short_header::INPUT_INITIATE_ROOT_FOUNDING,
            Self::ObserveRootFounding(_) => short_header::INPUT_OBSERVE_ROOT_FOUNDING,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_CONFIGURE => Ok(InputRoute::Configure),
            short_header::INPUT_CREATE_INTERCEPT_POLICY => {
                Ok(InputRoute::CreateInterceptPolicy)
            }
            short_header::INPUT_REPLACE_INTERCEPT_POLICY => {
                Ok(InputRoute::ReplaceInterceptPolicy)
            }
            short_header::INPUT_CANCEL_INTERCEPT_POLICY => {
                Ok(InputRoute::CancelInterceptPolicy)
            }
            short_header::INPUT_LIST_INTERCEPT_POLICIES => {
                Ok(InputRoute::ListInterceptPolicies)
            }
            short_header::INPUT_OBSERVE_INTERCEPT_POLICIES => {
                Ok(InputRoute::ObserveInterceptPolicies)
            }
            short_header::INPUT_RETRACT_INTERCEPT_POLICY_OBSERVATION => {
                Ok(InputRoute::RetractInterceptPolicyObservation)
            }
            short_header::INPUT_FETCH_PARKED_REQUESTS => {
                Ok(InputRoute::FetchParkedRequests)
            }
            short_header::INPUT_ANSWER_PARKED_REQUEST => {
                Ok(InputRoute::AnswerParkedRequest)
            }
            short_header::INPUT_OBSERVE_PARKED_AUTHORIZATIONS => {
                Ok(InputRoute::ObserveParkedAuthorizations)
            }
            short_header::INPUT_SUBMIT_AUTHORIZATION_APPROVAL => {
                Ok(InputRoute::SubmitAuthorizationApproval)
            }
            short_header::INPUT_ACCEPT_ROOT_FOUNDING => {
                Ok(InputRoute::AcceptRootFounding)
            }
            short_header::INPUT_INITIATE_ROOT_FOUNDING => {
                Ok(InputRoute::InitiateRootFounding)
            }
            short_header::INPUT_OBSERVE_ROOT_FOUNDING => {
                Ok(InputRoute::ObserveRootFounding)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ConfigurationApplied(_) => OutputRoute::ConfigurationApplied,
            Self::InterceptPolicyCreated(_) => OutputRoute::InterceptPolicyCreated,
            Self::InterceptPolicyReplaced(_) => OutputRoute::InterceptPolicyReplaced,
            Self::InterceptPolicyCancelled(_) => OutputRoute::InterceptPolicyCancelled,
            Self::InterceptPoliciesListed(_) => OutputRoute::InterceptPoliciesListed,
            Self::InterceptPolicyObservationOpened(_) => {
                OutputRoute::InterceptPolicyObservationOpened
            }
            Self::InterceptPolicyObservationRetracted(_) => {
                OutputRoute::InterceptPolicyObservationRetracted
            }
            Self::ParkedRequestsFetched(_) => OutputRoute::ParkedRequestsFetched,
            Self::ParkedRequestAnswered(_) => OutputRoute::ParkedRequestAnswered,
            Self::ParkedAuthorizations(_) => OutputRoute::ParkedAuthorizations,
            Self::AuthorizationApprovalStored(_) => {
                OutputRoute::AuthorizationApprovalStored
            }
            Self::ConfigurationRefused(_) => OutputRoute::ConfigurationRefused,
            Self::OperationUnimplemented(_) => OutputRoute::OperationUnimplemented,
            Self::RootFoundingConfirmed(_) => OutputRoute::RootFoundingConfirmed,
            Self::RootFoundingRefused(_) => OutputRoute::RootFoundingRefused,
            Self::RootFoundingObserved(_) => OutputRoute::RootFoundingObserved,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ConfigurationApplied(_) => short_header::OUTPUT_CONFIGURATION_APPLIED,
            Self::InterceptPolicyCreated(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_CREATED
            }
            Self::InterceptPolicyReplaced(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_REPLACED
            }
            Self::InterceptPolicyCancelled(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_CANCELLED
            }
            Self::InterceptPoliciesListed(_) => {
                short_header::OUTPUT_INTERCEPT_POLICIES_LISTED
            }
            Self::InterceptPolicyObservationOpened(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_OBSERVATION_OPENED
            }
            Self::InterceptPolicyObservationRetracted(_) => {
                short_header::OUTPUT_INTERCEPT_POLICY_OBSERVATION_RETRACTED
            }
            Self::ParkedRequestsFetched(_) => {
                short_header::OUTPUT_PARKED_REQUESTS_FETCHED
            }
            Self::ParkedRequestAnswered(_) => {
                short_header::OUTPUT_PARKED_REQUEST_ANSWERED
            }
            Self::ParkedAuthorizations(_) => short_header::OUTPUT_PARKED_AUTHORIZATIONS,
            Self::AuthorizationApprovalStored(_) => {
                short_header::OUTPUT_AUTHORIZATION_APPROVAL_STORED
            }
            Self::ConfigurationRefused(_) => short_header::OUTPUT_CONFIGURATION_REFUSED,
            Self::OperationUnimplemented(_) => {
                short_header::OUTPUT_OPERATION_UNIMPLEMENTED
            }
            Self::RootFoundingConfirmed(_) => {
                short_header::OUTPUT_ROOT_FOUNDING_CONFIRMED
            }
            Self::RootFoundingRefused(_) => short_header::OUTPUT_ROOT_FOUNDING_REFUSED,
            Self::RootFoundingObserved(_) => short_header::OUTPUT_ROOT_FOUNDING_OBSERVED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_CONFIGURATION_APPLIED => {
                Ok(OutputRoute::ConfigurationApplied)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_CREATED => {
                Ok(OutputRoute::InterceptPolicyCreated)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_REPLACED => {
                Ok(OutputRoute::InterceptPolicyReplaced)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_CANCELLED => {
                Ok(OutputRoute::InterceptPolicyCancelled)
            }
            short_header::OUTPUT_INTERCEPT_POLICIES_LISTED => {
                Ok(OutputRoute::InterceptPoliciesListed)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_OBSERVATION_OPENED => {
                Ok(OutputRoute::InterceptPolicyObservationOpened)
            }
            short_header::OUTPUT_INTERCEPT_POLICY_OBSERVATION_RETRACTED => {
                Ok(OutputRoute::InterceptPolicyObservationRetracted)
            }
            short_header::OUTPUT_PARKED_REQUESTS_FETCHED => {
                Ok(OutputRoute::ParkedRequestsFetched)
            }
            short_header::OUTPUT_PARKED_REQUEST_ANSWERED => {
                Ok(OutputRoute::ParkedRequestAnswered)
            }
            short_header::OUTPUT_PARKED_AUTHORIZATIONS => {
                Ok(OutputRoute::ParkedAuthorizations)
            }
            short_header::OUTPUT_AUTHORIZATION_APPROVAL_STORED => {
                Ok(OutputRoute::AuthorizationApprovalStored)
            }
            short_header::OUTPUT_CONFIGURATION_REFUSED => {
                Ok(OutputRoute::ConfigurationRefused)
            }
            short_header::OUTPUT_OPERATION_UNIMPLEMENTED => {
                Ok(OutputRoute::OperationUnimplemented)
            }
            short_header::OUTPUT_ROOT_FOUNDING_CONFIRMED => {
                Ok(OutputRoute::RootFoundingConfirmed)
            }
            short_header::OUTPUT_ROOT_FOUNDING_REFUSED => {
                Ok(OutputRoute::RootFoundingRefused)
            }
            short_header::OUTPUT_ROOT_FOUNDING_OBSERVED => {
                Ok(OutputRoute::RootFoundingObserved)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Configure",
        "CreateInterceptPolicy",
        "ReplaceInterceptPolicy",
        "CancelInterceptPolicy",
        "ListInterceptPolicies",
        "ObserveInterceptPolicies",
        "RetractInterceptPolicyObservation",
        "FetchParkedRequests",
        "AnswerParkedRequest",
        "ObserveParkedAuthorizations",
        "SubmitAuthorizationApproval",
        "AcceptRootFounding",
        "InitiateRootFounding",
        "ObserveRootFounding",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
